rules:

  # Code checks
  #
  eqeqeq:
    - 2
  no-dupe-args:
    - 2
  no-dupe-keys:
    - 2
  no-duplicate-case:
    - 2
  no-func-assign:
    - 2
  no-inner-declarations:
    - 2
  no-unreachable:
    - 2
  no-redeclare:
    - 2
  no-shadow:
    - 2
  no-undef:
    - 2
  no-eval:
    - 2
  valid-typeof:
    - 2
  no-use-before-define:
    - 1
    - nofunc
  no-unused-vars:
    - 1
    -
      vars: all
      args: none
  no-loop-func:
    - 1
  no-console:
    - 1
  no-alert:
    - 1
  no-debugger:
    - 1
  no-undefined:
    - 1
  no-process-env:
    - 1
  no-var:
    - 1

  # Punctation rules
  #
  semi:
    - 2
    - always
  linebreak-style:
    - 2
    - unix
  no-extra-semi:
    - 2
  curly:
    - 2
  comma-dangle:
    - 1
    - always-multiline
  quotes:
    - 1
    - single

  # Spacing rules
  #
  no-spaced-func:
    - 2
  no-irregular-whitespace:
    - 2
  indent:
    - 1
    - 2
    -
      SwitchCase: 1
      VariableDeclarator:
        var: 2
        let: 2
        const: 3
  brace-style:
    - 1
    - 1tbs
    -
      allowSingleLine: true
  no-multi-spaces:
    - 1
  key-spacing:
    - 1
    -
      beforeColon: false
      afterColon: true
  space-before-keywords:
    - 1
    - always
  space-after-keywords:
    - 1
    - always
  arrow-spacing:
    - 1
    -
      before: true
      after: true
  space-infix-ops:
    - 1
  object-curly-spacing:
    - 1
    - always
    -
      objectsInObjects: true
      arraysInObjects: true
  space-in-parens:
    - 1
    - never
  eol-last:
    - 1

  # Coding helpers rules
  #
  strict:
    - 2
    - never
  complexity:
    - 1
    - 4
  max-depth:
    - 1
    - 5
  max-nested-callbacks:
    - 1
    - 4
  max-len:
    - 1
    - 100
    - 4
    -
      ignoreComments: true

  # ES6 rules
  #
  generator-star-spacing:
    - 1
  object-shorthand:
    - 1
    - always
  prefer-template:
    - 0

  # React custom rules
  #
  react/jsx-uses-react:
    - 2
  react/jsx-uses-vars:
    - 2
  react/react-in-jsx-scope:
    - 2

#
# Custom parser to handle ES7
#
parser: babel-eslint

#
# Environments
#
env:
  es6: true
  node: true
  browser: true

#
# ECMA features
#
ecmaFeatures:
  jsx: true
  modules: true
  blockBindings: true

#
# Plugins for additional rules
#
plugins:
  - react
  - babel

#
# Project wise globals
#
globals:
  __CLIENT__: true
  CONFIG: true
