instrumentation:
  root: .
  extensions:
    - .js
    - .jsx
  default-excludes: true
  excludes: ['public', 'server.js', 'webpack.config.js', '**/*.spec.js']
  include-all-sources: true
extensions:
  - .js
  - .jsx
reporting:
  dir: ./coverage
  reports:
    - text
    - html
